language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
# Gradle을 통해 의존성 받을 시 해당 디렉토리에 캐시하여 다음 배포시부터 같은 의존성은 받지 않음
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# 위에서 설정한 브랜치에서(master) push되었을 때 수행하는 명령어
script: "./gradlew clean build"

# gradlew 권한설정
before_install:
  - chmod +x gradlew
#  - zip -r spring-portfolio *
#  - mkdir -p deploy
#  - mv spring-portfolio.zip deploy/spring-portfolio.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: spring-portfolio # S3 버킷명
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
#    local_dir: deploy # before_deploy에서 생성한 디렉토리 내용들만 S3로 전송
    wait-until-deployed: true
    on:
      repo: Gunggo/profile #Github 주소
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: spring-portfolio # S3 버킷
    key: spring-portfolio.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: spring-portfolio # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: spring-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: Gunggo/profile
      branch: master

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - gusehdqkd@gmail.com