# Test
spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---

spring:
  profiles: local
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  http:
    encoding:
      charset: UTF-8
      force: true