spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local

  devtools:
    livereload:
      enabled: true
      port: 35729

# real 환경
---
spring:
  profiles: set1
server:
  port: 8081

---
spring:
  profiles: set2
server:
  port: 8082
