spring:
  profiles:
    active: local # 기본 환경 선택

  datasource:
      url: jdbc:log4jdbc:mariadb://studywebservice.cdbsdzraucna.ap-northeast-2.rds.amazonaws.com:3306/portfolio
      username: admin
      password: "*Qkdehd6148"
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      driver-class-name: org.mariadb.jdbc.Driver
mybatis:
  type-aliases-package: com.study.introduction.**.mapper
  mapper-locations: com.study.introduction.**.mapper.*.xml
  configuration:
    map-underscore-to-camel-case: true
