spring:
  profiles:
    active: local # 기본 환경 선택

# 로컬 환경
---

spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update
    showSql: true
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jwt:
    secret: govlepel@$&

# 서버 환경
---

spring:
  profiles: server

  datasource:
    url: jdbc:log4jdbc:mariadb://studywebservice.cdbsdzraucna.ap-northeast-2.rds.amazonaws.com:3306/portfolio
    username: admin
    password: "*Qkdehd6148"
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mybatis:
  type-aliases-package: com.study.introduction.**.mapper
  mapper-locations: com.study.introduction.**.mapper.*.xml
  configuration:
    map-underscore-to-camel-case: true

